// Coloring book scene prompts organized by category
// Each prompt describes a scene/activity to render the subject in

export const locationPrompts = [
  "Sipping espresso at a Parisian sidewalk cafe",
  "Walking through a neon-lit cyber city",
  "Reading on a rainy window seat",
  "Shopping in a bustling Tokyo market",
  "Waiting for a train in a vintage subway station",
  "Stargazing from a rooftop garden",
  "Studying in a grand old library",
  "Sunbathing on a Mediterranean yacht",
  "Grocery shopping in a retro 1950s store",
  "Walking a dog in a suburban autumn park",
  "Working late in a high-rise office",
  "Meditating in a Zen garden",
  "Dancing in a crowded underground club",
  "Praying in a sunlit cathedral",
  "Browsing vinyl records in a dusty shop",
  "Eating street food at a night carnival",
  "Sitting around a bonfire on the beach",
  "Watching a movie at a drive-in theater",
  "Commuting on a busy ferry boat",
  "Picnicking in a field of lavender",
  "Standing on a misty pier at dawn",
  "Wandering through a hall of mirrors",
  "Buying flowers at a Sunday market",
  "Crossing a busy intersection in New York",
  "Relaxing in a natural hot spring",
  "Dining in an underwater restaurant",
  "Walking down a cobblestone alleyway",
  "Sitting in a retro diner booth",
  "Inspecting art in a modern white gallery",
  "Swinging on a porch in the countryside",
  "Waiting in an airport terminal",
  "Watching the sunset from a lighthouse",
  "Walking through a bamboo forest",
  "Skating on a frozen pond",
  "Exploring an abandoned warehouse",
  "Buying bread at a French bakery",
  "Sitting in a treehouse reading a book",
  "Walking the red carpet at a premiere",
  "Standing on the deck of a spaceship",
  "Cheering in a massive football stadium",
  "Playing slots in a Las Vegas casino",
  "Walking through a corn maze",
  "Sitting by a fireplace in a log cabin",
  "Hiding in a blanket fort",
  "Walking through a botanical greenhouse",
  "Standing in a vast desert at twilight",
  "Shopping in a futuristic mall",
  "Sitting at a bus stop in the rain",
  "Walking through a vineyard",
  "Looking out from a penthouse balcony",
  "Exploring a dusty attic",
  "Standing in a field of sunflowers",
  "Waiting in a hospital waiting room",
  "Walking through a misty graveyard",
  "Sitting at a chaotic stock exchange desk",
  "Relaxing in a sauna",
  "Walking along a boardwalk",
  "Standing in a server room with blue lights",
  "Eating lunch on a construction beam",
  "Walking through an aquarium tunnel",
  "Sitting in a quaint tea room",
  "Standing in a luscious jungle clearing",
  "Walking through a snowy village",
  "Sitting in a frantic newsroom",
  "Standing at the edge of a cliff",
  "Walking through a tunnel of cherry blossoms",
  "Sitting in a barber shop chair",
  "Standing in a massive hangar",
  "Walking through a chaotic bazaar",
  "Sitting in a luxury hotel lobby",
  "Standing in a wheat field before a storm",
  "Walking through a scientific laboratory",
  "Sitting in a sensory deprivation tank",
  "Standing on a gladiator arena floor",
  "Walking through a pumpkin patch",
  "Sitting in a court jury box",
  "Standing in a lavender field",
  "Walking through a music festival crowd",
  "Sitting in a classic convertible",
  "Standing in a chaotic kitchen",
  "Walking through a marble government hall",
  "Sitting in a recording booth",
  "Standing on a foggy moor",
  "Walking through a street art alley",
  "Sitting in a planetarium",
  "Standing in a serene monastery",
  "Walking through a luxury boutique",
  "Sitting in a cluttered garage",
  "Standing on a golf course green",
  "Walking through dense fog",
  "Sitting in a rustic tavern",
  "Standing in a coral reef underwater",
  "Walking through a tulip field",
  "Sitting in a lecture hall",
  "Standing in a vast salt flat",
  "Walking through a rainy alley noir-style",
  "Sitting in a futuristic pod",
  "Standing in a lush oasis",
  "Walking through a christmas market",
  "Sitting on a jagged rock by the ocean",
];

export const hobbyPrompts = [
  "Playing a grand piano",
  "Painting on an easel",
  "Knitting a colorful scarf",
  "Throwing pottery on a wheel",
  "Playing chess in a park",
  "Cooking a gourmet meal",
  "Gardening in a backyard",
  "Strumming an acoustic guitar",
  "Writing in a leather journal",
  "Building a robot",
  "Practicing ballet at a barre",
  "Playing video games on a couch",
  "Sewing a dress",
  "Taking photographs with a DSLR",
  "Skateboarding at a park",
  "Baking cupcakes",
  "Doing yoga on a mat",
  "Woodworking at a bench",
  "Playing poker with friends",
  "Arranging flowers in a vase",
  "Coding on a laptop",
  "Fishing by a lake",
  "Playing the drums",
  "Sculpting clay",
  "Birdwatching with binoculars",
  "Playing tennis",
  "Calligraphy writing",
  "Mixing music as a DJ",
  "Restoring a vintage car",
  "Playing board games",
  "Origami folding",
  "Boxing in a ring",
  "Tying fishing flies",
  "Playing the violin",
  "Brewing craft beer",
  "Cosplaying a fantasy character",
  "Solving a jigsaw puzzle",
  "Playing basketball",
  "Tattooing a design",
  "Flying a drone",
  "Playing the saxophone",
  "Making jewelry",
  "Scrapbooking photos",
  "Playing billiards pool",
  "Welding metal art",
  "Bowling a strike",
  "Collecting stamps with a magnifying glass",
  "Playing the flute",
  "Model building planes or ships",
  "Ballroom dancing",
  "Beekeeping",
  "Playing soccer",
  "Glass blowing",
  "Tarot card reading",
  "Playing the harp",
  "Soap making",
  "Archery target practice",
  "Playing volleyball",
  "Candle making",
  "Quilting a blanket",
  "Playing the trumpet",
  "Magic tricks with cards",
  "Bonsai tree trimming",
  "Playing rugby",
  "Leatherworking",
  "Singing into a microphone",
  "Metal detecting on a beach",
  "Playing ping pong",
  "Embroidery stitching",
  "Wine tasting",
  "Playing the cello",
  "Latte art pouring",
  "Fencing duel",
  "Podcast recording",
  "Playing badminton",
  "Cake decorating",
  "Whittling wood",
  "Playing the harmonica",
  "Disc golf throwing",
  "3D printing objects",
  "Playing cricket",
  "Stone carving",
  "Telescope viewing",
  "Playing the accordion",
  "Crossfit training",
  "Mosaic tile laying",
  "Playing ice hockey",
  "Candle carving",
  "Terrarium building",
  "Playing the banjo",
  "Salsa dancing",
  "Making sushi",
  "Playing ultimate frisbee",
  "Screen printing t-shirts",
  "Acting on stage",
  "Playing the ukulele",
  "Perfume mixing",
  "Playing darts",
  "Cookie decorating",
  "Restoring antique furniture",
];

export const adventurePrompts = [
  "Climbing a snowy mountain peak",
  "Scuba diving with turtles",
  "Hiking a dense forest trail",
  "Paragliding over a valley",
  "Kayaking down a rushing river",
  "Camping under the Milky Way",
  "Exploring a dark cave",
  "Surfing a massive wave",
  "Backpacking through Europe",
  "Riding a camel in the desert",
  "Zip-lining through a jungle canopy",
  "Skiing down a fresh slope",
  "Safari jeep driving near lions",
  "Bungee jumping off a bridge",
  "Sailing a boat in open water",
  "Rock climbing a sheer cliff",
  "Snorkeling in a coral reef",
  "Riding a motorcycle on a coastal road",
  "Hot air ballooning at sunrise",
  "Trekking to a hidden waterfall",
  "Snowboarding a half-pipe",
  "Rafting white water rapids",
  "Exploring ancient ruins",
  "Skydiving freefall",
  "Horseback riding on a beach",
  "Spelunking in a crystal cavern",
  "Paddleboarding on a calm lake",
  "Hang gliding off a cliff",
  "Dog sledding in the arctic",
  "Canyoneering through narrow slots",
  "Riding an ATV in mud",
  "Freediving into the blue hole",
  "Walking across a suspension bridge",
  "Sandboarding down a dune",
  "Jet skiing on the ocean",
  "Exploring a shipwreck",
  "Mountain biking a rocky trail",
  "Ice climbing a frozen waterfall",
  "Parasailing behind a boat",
  "Hitchhiking on a lonely road",
  "Discovering a lost temple",
  "Windsurfing in high winds",
  "Navigating a swamp boat",
  "Rappelling down a building",
  "Base jumping from a tower",
  "Jungle trekking with a machete",
  "Flying a small bush plane",
  "Cliff diving into the sea",
  "Cave diving underwater",
  "Riding a mechanical bull",
  "Exploring a glacier crevasse",
  "Kitesurfing on waves",
  "Tracking wildlife footprints",
  "Urban exploring a ghost town",
  "Riding a zipline over a canyon",
  "Deep sea fishing",
  "High-lining slackline between peaks",
  "Hoverboarding over water",
  "Exploring a lava tube",
  "Wakeboarding behind a boat",
  "Crossing a desert on foot",
  "Ice fishing on a frozen lake",
  "Searching for gold in a river",
  "Riding a roller coaster",
  "Exploring a dense mangrove",
  "Snowshoeing in deep powder",
  "Swimming with sharks in a cage",
  "Riding an ostrich racing",
  "Exploring a Mayan pyramid",
  "Bodyboarding close to shore",
  "Crossing a river on a log",
  "Riding a unicycle on a trail",
  "Exploring a subterranean tunnel",
  "Water skiing",
  "Glider flying",
  "Spear fishing",
  "Bouldering without ropes",
  "Riding a submarine",
  "Exploring a castle dungeon",
  "Tubing down a lazy river",
  "Parkour jumping between roofs",
  "Riding a Segway tour",
  "Exploring a crater",
  "Sledding down a steep hill",
  "Tree climbing with ropes",
  "Riding a horse through a canyon",
  "Exploring a secret bunker",
  "Wing-suit flying",
  "Canoeing a calm stream",
  "Monster truck driving",
  "Exploring a salt mine",
  "Rowing a crew shell",
  "Trapeze flying",
  "Riding a gondola in Venice",
  "Exploring a bioluminescent bay",
  "Zorbing rolling in a ball",
  "Walking a tightrope",
  "Riding a snowmobile",
  "Exploring a pirate cove",
  "Helicopter tour over a city",
];

// Get all prompts combined
export function getAllPrompts(): string[] {
  return [...locationPrompts, ...hobbyPrompts, ...adventurePrompts];
}

// Select random unique prompts from all categories
export function selectRandomPrompts(count: number): string[] {
  const allPrompts = getAllPrompts();
  const shuffled = [...allPrompts].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
